Loaded FD001 training data: 100 engines, 20,631 cycles total, 21 sensors. Computed RUL as each engine’s final cycle minus the current cycle

In [9]:
import pandas as pd

cols = ["unit", "cycle", "op1", "op2", "op3"] + [f"s{i}" for i in range(1, 22)]
train = pd.read_csv("../data/raw/train_FD001.txt", sep=r"\s+", header=None, names=cols)
train.head()

,unit,cycle,op1,op2,op3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [10]:
train["RUL"] = train.groupby("unit")["cycle"].transform("max") - train["cycle"]
train[train["unit"] == 1][["unit", "cycle", "RUL"]].tail()

     unit  cycle  RUL
187     1    188    4
188     1    189    3
189     1    190    2
190     1    191    1
191     1    192    0

In [15]:
engine_life = train.groupby("unit")["cycle"].max()
engine_life

unit
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycle, Length: 100, dtype: int64